# -*- coding: utf-8 -*-
"""l2-2 calculando quantidade de animais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPkp3Ifu6KBPPBzucNIs3SsDx1ckCRmu
"""

a = 13
v = 12
print(f"Número de avestruz: {a}")
print(f"Número de vacas: {v}")