# -*- coding: utf-8 -*-
"""l2-3 Calculando o valor da compra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZxxQRu5MCBBurksZTYPNjS5rusFMGcD
"""

qnt_pao = float(input())
val_pao = float(input())
qnt_queijo = float(input())
val_queijo = float(input())

total_pao = qnt_pao*val_pao
total_queijo = qnt_queijo*val_queijo
total = total_pao + total_queijo

print(f'Pao: R$ {total_pao}')
print(f'Queijo: R$ {total_queijo}')
print(f'Total: R$ {total}')