# -*- coding: utf-8 -*-
"""l3_1_validacao_de_senhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGRkd9osCNxcm9dWHgIhINwhwWL_3grj
"""

senha = input()
confirma_senha = input()

if (senha == confirma_senha and len(senha) > 3 and len(senha) < 9):
  print("Senha válida")
else:
  print("Senha inválida")