# -*- coding: utf-8 -*-
"""l3_2_calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDeNvXQaYZCOO76DxslGwThulgOhlSMa
"""

#função que efetua o cálculo de acordo com o operador passado como parâmetro
def calculadora(n1,n2,operador):
  if (operador == '+'):
    resultado = n1+n2
  elif (operador == '-'):
    resultado = n1-n2
  elif (operador == '*'):
    resultado = n1*n2
  else:
    resultado = n1/n2

  return round(resultado,1)

#transforma a entrada numa lista chamada 'calculo' contendo 3 elementos: n1, n2 e operador, respectivamente
calculo = input().split()
n1 = float(calculo[0])
n2 = float(calculo[2])
operador = calculo[1]

#chama a função 'calculadora' e armazena valor na variável 'resultado'
resultado = calculadora(n1, n2, operador)

#saída de acordo com o run.codes
print (f'{calculo[0]} {operador} {calculo[2]} = {resultado}')