# -*- coding: utf-8 -*-
"""l6_1_separando_numeros_em_listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/rayfrance/09629bde3eff07d526487d13334714a6/l6_1_separando_numeros_em_listas.ipynb
"""

limite_inferior = int(input())
limite_superior = int(input())

n=0
while (n%2 == 0):
  n = int(input())

lista = range(limite_inferior,limite_superior)
primos = []
pares = []
divisiveis_por_n = []

for i in lista:
  divisores = []
  for j in range(1,i+1):
    if (i%j == 0):
      divisores.append(j)

  if (i%2 == 0):
    pares.append(i)

  if (len(divisores) <= 2):
    primos.append(i)

  if (i%n == 0):
    divisiveis_por_n.append(i)

print(primos)
print(pares)
print(divisiveis_por_n)